Upgrades huggingface_hub to solve ImportError.
ImportError: huggingface-hub>=0.34.0,<1.0 is required for a normal functioning of this module, but found huggingface-hub==0.33.4.
Try: `pip install transformers -U` or `pip install -e '.[dev]'` if you're working with git main