Removes parameter logging callback to resolve error.
File "/slollmasr/utils/callbacks/log_trainable_params_callback.py", line 60, in on_train_start
    trainer.logger.experiment.summary[key] = value
TypeError: 'method' object does not support item assignment