Makes batch_size a required argument to fix IndexError.
Traceback (most recent call last):
  File "/slollmasr/main.py", line 96, in <module>
    new_scores, used_alpha, used_beta = method.run(dataset, alpha, beta)
  File "/slollmasr/methods/CausalReScorer.py", line 52, in run
    input_ids, input_mask = input_ids[:, :max_len_in_batch], input_mask[:, :max_len_in_batch]
IndexError: too many indices for tensor of dimension 1