Sets max new tokens.
ValueError: Input length of input_ids is 283, but `max_length` is set to 20. This can lead to unexpected behavior. You should consider increasing `max_length` or, better yet, setting `max_new_tokens.